# This is the final, complete Cloud Build configuration file for your CI/CD pipeline.
# It now points to the correct source code directories.

steps:
# --- Stage 1: Build and Deploy the BERT Sentiment API (Cloud Run Service) ---

# This step deploys the final, working API code from the 'bert-api-fix' directory.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'bert-sentiment-service'
  - '--source'
  - './bert-sentiment-function/vertex-ai-pipeline/bert-api-fix' # <-- CORRECTED PATH
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--memory=2Gi'
  - '--cpu=2'

# --- Stage 2: Deploy the Sentiment Processor (Cloud Function) ---

# This step deploys the final, working function code from the 'cloud-function' directory.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'bert-sentiment-processor'
  - '--gen2'
  - '--runtime=python311'
  - '--region'
  - 'us-central1'
  - '--source=./bert-sentiment-function/vertex-ai-pipeline/cloud-function' # <-- CORRECTED PATH
  - '--entry-point=bert_sentiment_processor'
  - '--trigger-topic=bert-sentiment-requests'
  - '--set-env-vars=BERT_API_URL=https://bert-sentiment-service-121496194098.us-central1.run.app,BUCKET_NAME=ms-gcu-dissertation-bert-predictions'

# This setting tells Cloud Build to only store the logs in Google Cloud Logging.
options:
  logging: CLOUD_LOGGING_ONLY